[meta]
name     = "Map Playlist"
author   = "Fort-TM"
category = "Utilities"
version  = "0.1"

[script]
dependencies = [ "NadeoServices", "Controls" ]
optional_dependencies = [ "WarriorMedals" ]
timeout = 10000
